package com.springboot.lebron.apis;

import com.springboot.lebron.model.User;
import com.springboot.lebron.model.UserRepository;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path="/api")
public class MainApiController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    //returns true if the email and password match
    // http://localhost:8080/api/login?email=bseager21@gmail.com&password=admin
    @GetMapping(path="/login")
    public @ResponseBody
    String loginApiController(@RequestParam String email, @RequestParam String password) {
        User user = userRepository.findByEmail(email);
        if(user.getPassword().equals(password)){
            return "true";
        }
        else{
            return "false";
        }
    }
}
